sudo apt-get install -y \
    gcc \
    g++ \
    autoconf \
    bison \
    re2c \
    locales \
    locales-all \
    ldap-utils \
    openssl \
    libgmp-dev \
    libicu-dev \
    libtidy-dev \
    libenchant-2-dev \
    libsasl2-dev \
    libxpm-dev \
    libzip-dev \
    libbz2-dev \
    libsqlite3-dev \
    libwebp-dev \
    libonig-dev \
    libcurl4-openssl-dev \
    libxml2-dev \
    libxslt1-dev \
    libpq-dev \
    libreadline-dev \
    libldap2-dev \
    libsodium-dev \
    libmm-dev \
    libsnmp-dev \
    snmpd \
    freetds-dev \
    dovecot-core \
    dovecot-pop3d \
    dovecot-imapd \
    sendmail \
    firebird-dev \
    liblmdb-dev \
    libtokyocabinet-dev \
    libdb-dev \
    libqdbm-dev \
    libjpeg-dev \
    libpng-dev \
    libfreetype-dev \
    quilt \
    pbuilder

wget https://manpages.ubuntu.com/manpages.gz/noble/man1/pdebuild.1.gz
gzip -d pdebuild.1.gz
which pdebuild